apiVersion: v1
kind: Service
metadata:
  name: rental-api
  labels:
    app: rental-api
spec:
  type: LoadBalancer  # Change to ClusterIP if using Ingress
  ports:
  - port: 80
    targetPort: 8087
    protocol: TCP
    name: http
  selector:
    app: rental-api
